@Fornecedores_WebAPI_HostAddress = http://localhost:5274

### Retorna todos os fornecedores
GET {{Fornecedores_WebAPI_HostAddress}}/fornecedores
Accept: application/json

### Retorna um fornecedor específico pelo ID
GET {{Fornecedores_WebAPI_HostAddress}}/fornecedores/1
Accept: application/json

### Adiciona um novo fornecedor
POST {{Fornecedores_WebAPI_HostAddress}}/fornecedores
Content-Type: application/json
{
  "nome": "Fornecedor Teste",
  "email": "teste@fornecedor.com",
}

### Atualiza um fornecedor existente pelo ID
PUT {{Fornecedores_WebAPI_HostAddress}}/fornecedores/1
Content-Type: application/json
{
  "nome": "Fornecedor Atualizado",
  "email": "atualizado@fornecedor.com",
}

### Remove um fornecedor pelo ID
DELETE {{Fornecedores_WebAPI_HostAddress}}/fornecedores/1

